env:
    global:
        - REPO_DIR=.
        # Commit from your-project that you want to build
        #- BUILD_COMMIT=v0.1.0
        # pip dependencies to _build_ your project
        #- BUILD_DEPENDS="Cython numpy"
        # pip dependencies to _test_ your project.  Include any dependencies
        # that you need, that are also specified in BUILD_DEPENDS, this will be
        # a separate install.
        - TEST_DEPENDS="pytest"
        - PLAT=x86_64
        - CONFIG_PATH="ci/multibuild_config.sh"

language: python
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.5
sudo: required
dist: trusty
services: docker

cache:
  directories:
    - $HOME/.ccache

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    - os: linux  # Bundle 32 bit library. Python 2.7 just to test it works there.
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
        - USE_CCACHE=1
        - FREETYPEPY_BUNDLE_FT=1
    - os: linux  # Bundle 64 bit library.
      env:
        - MB_PYTHON_VERSION=3.6
        - USE_CCACHE=1
        - FREETYPEPY_BUNDLE_FT=1
    - os: linux  # No bundling.
      env:
        - MB_PYTHON_VERSION=3.6
        - BUILD_SDIST=1
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - USE_CCACHE=1
        - FREETYPEPY_BUNDLE_FT=1

before_install:
    - source ci/multibuild/common_utils.sh
    - source ci/multibuild/travis_steps.sh
    # Pass FREETYPEPY_BUNDLE_FT environment variable to container.
    - source ci/custom_docker.sh
    - before_install

install:
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
  # Copy compiled wheels to dist/ where Travis `dpl` tool can find them and 
  # upload to PyPI
  - if [ -n "$TRAVIS_TAG" ]; then mkdir -p dist; cp wheelhouse/*.whl dist; fi
  - if [ -n "$TRAVIS_TAG" ] && [ -n "$BUILD_SDIST" ]; then python setup.py sdist; fi

deploy:
  # Deploy to PyPI on tags. Since the hard work of building wheels is already 
  # done, we need to defeat some of Travis' automation.
  provider: pypi
  on:
    repo: rougier/freetype-py  # Prevent triggering from forks.
    tags: true
    all_branches: true
  user: NicolasRougier
  password:
    secure: DcRKZzasCgo6eCZ5CN/tVngfCcQY7+S8MKpKIGOx4FgfrNd3P3WIxXWqHeIdDpJZKO8wqW9OIrbEvzozMvj6Y/ckcxUsAaPj3zBn80XB9oGjGLHlFCVp39rTQ3BJAOq+0UwaRQAasTErf/0Q1k1LSOttmIGW41u5zNDohwaGxgc=
  skip_cleanup: true  # Prevent deletion of dist/*.
  distributions: check  # Dummy argument so dists aren't rebuilt by dpl.
